name: start_app
description: A Start Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  english_words: ^3.1.0

  #状态变化
  provider: ^5.0.0
  # 将展示层的代码与业务逻辑分开，从而使您的代码快速，易于测试且可重复使用
  # https://github.com/felangel/bloc/tree/master/packages/bloc
  bloc: ^7.0.0
  # 强大的Flutter Widgets可与bloc配合使用，以构建快速，反应灵活的移动端应用程序
  # https://github.com/felangel/bloc/tree/master/packages/flutter_bloc
  flutter_bloc: ^7.0.0
  # Redux for Dart 将泛型用于类型化状态。
  # https://github.com/fluttercommunity/redux.dart
  redux: ^5.0.0
  # 结合redux使用
  # https://github.com/brianegan/flutter_redux
  flutter_redux: ^0.8.2

  #  #国际化包
  #  intl: ^0.15.8
  #  #国际化工具 arb文件
  #  intl_translation: ^0.17.6
  flutter_localizations:
    sdk: flutter

  ########### 网络相关 ###########
  #网络请求 https://github.com/dart-lang/http
  http: ^0.12.0
  #网络请求 https://github.com/flutterchina/dio
  dio: ^3.0.10
  #cookie管理 https://github.com/flutterchina/dio/tree/master/plugins/cookie_manager
  dio_cookie_manager: 1.0.0
  #dio_cookie_manager需要此依赖 https://github.com/flutterchina/cookie_jar
  cookie_jar: ^1.0.1
  #网络连接检测
  connectivity: ^0.3.2
  #接口服务封装工具  https://github.com/trevorwang/retrofit.dart
  #retrofit: any

  #路由工具 https://github.com/lukepighetti/fluro
  fluro: ^2.0.3


  # 图片缓存 https://github.com/renefloor/flutter_cached_network_image
  cached_network_image: ^2.0.0

  ########### UI相关 ###########
  # 下拉刷新，上拉加载  https://github.com/peng8350/flutter_pulltorefresh
  pull_to_refresh: ^2.0.0
  # 轮播图 https://github.com/best-flutter/flutter_swiper
  flutter_swiper: ^1.1.6
  # 丰富的加载Loading样式 https://github.com/jogboms/flutter_spinkit
  flutter_spinkit: ^5.0.0
  #评价评分
  flutter_rating_bar: ^2.0.0+2
  # 图片浏览 https://github.com/fireslime/photo_view
  photo_view: 0.11.1
  #红点 https://github.com/yako-dev/flutter_badges
  badges: 2.0.1

  ########### 工具相关 ###########
  #吐司 https://github.com/PonnamKarthik/FlutterToast
  fluttertoast: ^8.0.7




  ########### 其它相关 ###########
  #日志打印 https://github.com/leisim/logger
  logger: ^1.0.0
  #数据存储
  shared_preferences: ^2.0.5
  #存储路径
  path_provider: ^2.0.0
  #json转model
  #json_to_model: ^1.4.0
  #apn_json2model: ^1.0.0
  json_annotation: ^3.0.1

  # WebView插件 https://pub.flutter-io.cn/packages/flutter_webview_plugin
  flutter_webview_plugin: ^0.3.11
  # WebView插件 https://github.com/flutter/plugins/tree/master/packages/webview_flutter
  webview_flutter: ^2.0.8
  # 启动URL的插件 https://github.com/flutter/plugins/tree/master/packages/url_launcher
  url_launcher: 6.0.3

  # 不必overrides == and hashCode，节省时间
  equatable: ^2.0.2

  # 待了解 支付宝 ： tobias 微信 fluwx

dev_dependencies:
  flutter_test:
    sdk: flutter
  #retrofit_generator: any
  build_runner: ^1.9.0
  json_serializable: ^3.3.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # 加载页面图片资源
  assets:
    - assets/data/language_colors.json
    - assets/data/home_data.json
    - assets/images/
    - assets/images/2.0x/
    - assets/images/3.0x/
    - assets/weather/
    - assets/git/
    - assets/git/comment/
    - assets/git/guide/
    - assets/git/issue/
    - assets/git/profile/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
